global:
  scrape_interval: 30s
  evaluation_interval: 30s

remote_write:
  - url: http://mimir:9009/api/v1/push
    remote_timeout: 30s
    queue_config:
      max_samples_per_send: 1000
      max_shards: 1

scrape_configs:
  - job_name: 'postgres-exporter'
    scrape_timeout: 30s
    static_configs:
      - targets: ['postgres-exporter:9187']
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgres
